AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  dyno-db-test

  Sample SAM Template for dyno-db-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DynamoDBCRUDFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handle-data/
      Handler: dynamoCRUD.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CRUDApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  CRUDApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
